sudo: false

language: php

services:
  - memcached
  - mongodb
  - mysql
  - postgresql
  - redis-server

matrix:
  fast_finish: true
  include:
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: hhvm
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - psql -c 'DROP DATABASE IF EXISTS test;' -U postgres
  - psql -c 'create database test;' -U postgres

install:
  - ./tests/script/install.sh

script:
after_success:
  - bash <(curl -s https://codecov.io/bash)
